name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    name: Release and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
        node-version: '20.x'

    - name: Run release script
      run: dotnet fsi build.fsx -p Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
