name: Update Fable NPM packages and release

on: workflow_dispatch

jobs:
  # Separate build job for JavaScript
  update-fable-packages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1

    - name: Install dependencies
      run: dotnet tool restore

    - name: Run release pipeline with auto-update option
      run: |
        dotnet fsi build.fsx -p AutoUpdate
